version: '3'

networks:
    web_network:
        driver: bridge

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            POSTGRES_DB: books
    
        volumes:
            - /pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"